# -*- coding: utf-8 -*-
"""product-recommendation-system-for-e-commerce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1us4aPhUeiX-QylZsQeKOyp4jrXT4WfQF

### Amar Shaw
* Computer Science Engineering,(August, 2019)

## Product Recommendation System for e-commerce businesses
A well developed recommendation system will help businesses improve their shopper's experience on website and result in better customer acquisition and retention.

The recommendation system, I have designed below is based on the journey of a new customer from the time he/she lands on the business’s website for the first time to when he/she makes repeat purchases.

The recommendation system is designed in 3 parts based on the business context:

* **Recommendation system part I:** Product pupularity based system targetted at new customers

* **Recommendation system part II:** Model-based collaborative filtering system based on customer's purchase history and ratings provided by other users who bought items similar items

* **Recommendation system part III:** When a business is setting up its e-commerce website for the first time withou any product rating

When a new customer without any previous purchase history visits the e-commerce website for the first time, he/she is recommended the most popular products sold on the company's website. Once, he/she makes a purchase, the recommendation system updates and recommends other products based on the purchase history and ratings provided by other users on the website. The latter part is done using collaborative filtering techniques.

## Recommendation System - Part I
### Product popularity based recommendation system targeted at new customers
* Popularity based are a great strategy to target the new customers with the most popular products sold on a business's website and is very useful to cold start a recommendation engine.
[[](http://)](http://)
* **Dataset : **[Amazon product review dataset](https://www.kaggle.com/skillsmuggler/amazon-ratings)

#### Importing libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# %matplotlib inline
plt.style.use("ggplot")

import sklearn
from sklearn.decomposition import TruncatedSVD

"""#### Loading the dataset"""

amazon_ratings = pd.read_csv(r'C:\Users\swapn\Desktop\dataset 2\amazon\amazon.csv')
amazon_ratings = amazon_ratings.dropna()
amazon_ratings.head()

amazon_ratings.shape

popular_products = pd.DataFrame(amazon_ratings.groupby('product_id')['rating'].count())
most_popular = popular_products.sort_values('rating', ascending=False)
most_popular.head(10)

most_popular.head(30).plot(kind = "bar")

"""** Analysis:**

* The above graph gives us the most popular products (arranged in descending order) sold by the business.

* For eaxmple, product, ID # B001MA0QY2 has sales of over 7000, the next most popular product, ID # B0009V1YR8 has sales of  3000, etc.

## Recommendation System - Part II
### Model-based collaborative filtering system

* Recommend items to users based on purchase history and similarity of ratings provided by other users who bought items to that of a particular customer.
* A model based collaborative filtering technique is closen here as it helps in making predictinfg products for a particular user by identifying patterns based on preferences from multiple user data.

#### Utility Matrix based on products sold and user reviews
**Utility Matrix : **An utlity matrix is consists of all possible user-item preferences (ratings) details represented as a matrix. The utility matrix is sparce as none of the users would buy all teh items in the list, hence, most of the values are unknown.
"""

# Subset of Amazon Ratings

amazon_ratings1 = amazon_ratings.head(10000)

amazon_ratings1
amazon_ratings1[amazon_ratings1['rating'] == '4.04.0']
# print(amazon_ratings1.dtypes)
amazon_ratings1['rating'] = pd.to_numeric(amazon_ratings1['rating'], errors='coerce')

ratings_utility_matrix = amazon_ratings1.pivot_table(values='rating', index='user_id', columns='product_id', fill_value=0)
ratings_utility_matrix.head()

"""As expected, the utility matrix obtaned above is sparce, I have filled up the unknown values wth 0."""

ratings_utility_matrix.shape

"""Transposing the matrix"""

X = ratings_utility_matrix.T
X.head()

X.shape

"""Unique products in subset of data"""

X1 = X

"""### Decomposing the Matrix"""

SVD = TruncatedSVD(n_components=10)
decomposed_matrix = SVD.fit_transform(X)
decomposed_matrix.shape

"""### Correlation Matrix"""

correlation_matrix = np.corrcoef(decomposed_matrix)
correlation_matrix.shape

"""correlation_matrix

### Isolating Product ID # 6117036094 from the Correlation Matrix

Assuming the customer buys Product ID # 6117036094 (randomly chosen)
"""

X.index[99]

"""Index # of product ID purchased by customer"""

i = "B08NW8GHCJ"

product_names = list(X.index)
product_ID = product_names.index(i)
product_ID

"""Correlation for all items with the item purchased by this customer based on items rated by other customers people who bought the same product"""

correlation_product_ID = correlation_matrix[product_ID]
correlation_product_ID.shape

"""### Recommending top 10 highly correlated products in sequence"""

Recommend = list(X.index[correlation_product_ID > 0.90])

# Removes the item already bought by the customer
Recommend.remove(i)

Recommend[0:9]

"""**Product Id # **
Here are the top 10 products to be displayed by the recommendation system to the above customer based on the purchase history of other customers in the website.

## Recommendation System - Part III
* For a business without any user-item purchase history, a search engine based recommendation system can be designed for users. The product recommendations can be based on textual clustering analysis given in product description.
* **Dataset : **[Home Depot's dataset with product dataset.](https://www.kaggle.com/c/home-depot-product-search-relevance/data)
"""

# Importing libraries

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score

"""### Item to item based recommendation system based on product description

Applicable when business is setting up its E-commerce website for the first time
"""

product_descriptions = amazon_ratings1
product_descriptions.shape

"""#### Checking for missing values"""

# Missing values

product_descriptions = product_descriptions.dropna()
product_descriptions.shape
product_descriptions.head()

product_descriptions1 = product_descriptions.head(500)
# product_descriptions1.iloc[:,1]

product_descriptions1["about_product"].head(10)

"""#### Feature extraction from product descriptions

Converting the text in product description into numerical data for analysis
"""

vectorizer = TfidfVectorizer(stop_words='english')
X1 = vectorizer.fit_transform(product_descriptions1["about_product"])
X1

"""#### Visualizing product clusters in subset of data"""

# Fitting K-Means to the dataset

X=X1

kmeans = KMeans(n_clusters = 10, init = 'k-means++')
y_kmeans = kmeans.fit_predict(X)
plt.plot(y_kmeans, ".")
plt.show()

"""F"""

# def print_cluster(i):
#     print("Cluster %d:" % i),
#     for ind in order_centroids[i, :10]:
#         print(' %s' % terms[ind]),
#     print

# ... the rest of your code ...

def print_cluster(i):
    print("Cluster %d:" % i),
    for ind in order_centroids[i, :10]:
        print(' %s' % terms[ind]),
    print

# labels_series = pd.Series(model.labels_, index=amazon_ratings1.index)
# cluster_products = amazon_ratings1[labels_series == prediction[0]]


# def show_recommendations(query):
#     # Transform the query to be in the same feature space as the products
#     Y = vectorizer.transform([query])

#     # Predict the cluster for the query
#     prediction = model.predict(Y)

#     # Create a labels series with the same index as amazon_ratings1
#     labels_series = pd.Series(model.labels_, index=amazon_ratings1.index)

#     # Get all product names and IDs from the predicted cluster
#     cluster_products = amazon_ratings1[labels_series == prediction[0]]

#     # Print the product names and IDs
#     for _, product in cluster_products.iterrows():
#         print(f"Product ID: {product['product_id']}, Product Name: {product['product_name']}")

"""## Output
* Recommendation of product based on the current product selected by user.
* To recommend related product based on, Frequently bought together.

#### Top words in each cluster based on product description
"""

# # # Optimal clusters is

# true_k = 10

# model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)
# model.fit(X1)

# print("Top terms per cluster:")
# order_centroids = model.cluster_centers_.argsort()[:, ::-1]
# terms = vectorizer.get_feature_names_out()
# for i in range(true_k):
#     print_cluster(i)

true_k = 10

# Vectorize the product names
product_names = amazon_ratings1['product_name']
X1 = vectorizer.fit_transform(product_names)

model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)
model.fit(X1)

print("Top terms per cluster:")
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names_out()
for i in range(true_k):
    print_cluster(i)

def print_cluster(i):
    print("Cluster %d:" % i),
    for ind in order_centroids[i, :10]:
        print(' %s' % terms[ind]),
    print

# def show_recommendations(product_name):
#     # Transform the query to be in the same feature space as the products
#     product_vector = vectorizer.transform([product_name])

#     # Predict the cluster for the query
#     prediction = model.predict(product_vector)

#     # Create a labels series with the same index as amazon_ratings1
#     labels_series = pd.Series(model.labels_, index=amazon_ratings1.index)

#     # Get all product names and IDs from the predicted cluster
#     cluster_products = amazon_ratings1[labels_series == prediction[0]]

#     # Print the product names and IDs
#     for _, product in cluster_products.iterrows():
#         print(f"Product ID: {product['product_id']}, Product Name: {product['product_name']}")

# # Now you can show recommendations for a product
# show_recommendations("Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)")

"""#### Predicting clusters based on key search words"""

# def show_recommendations(product):
#     #print("Cluster ID:")
#     Y = vectorizer.transform([product])
#     prediction = model.predict(Y)
#     #print(prediction)
#     print_cluster(prediction[0])

def show_recommendations(product_name):
    # Transform the query to be in the same feature space as the products
    product_vector = vectorizer.transform([product_name])

    # Predict the cluster for the product vector
    prediction = model.predict(product_vector)

    # Create a labels series with the same index as amazon_ratings1
    labels_series = pd.Series(model.labels_, index=amazon_ratings1.index)

    # Get all product names and IDs from the predicted cluster
    cluster_products = amazon_ratings1[labels_series == prediction[0]]

    # Remove the product itself from the recommendations
    cluster_products = cluster_products[cluster_products['product_name'] != product_name]
    
    recommendations = []
    # Print the product names and IDs
    for _, product in cluster_products.iterrows():
        # print(f"Product ID: {product['product_id']}, Product Name: {product['product_name']}")
        recommendations.append({
            'product_id': product['product_id'],
            'product_name': product['product_name']
            
        })
    
    return recommendations
        #  print(f"Product ID: {product['product_id']}, Product Name: {product['product_name']}")

"""* **Keyword : ** cutting tool"""

show_recommendations("iphone")



show_recommendations("")



